name: Java CI with Maven Deploy to heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_webapi:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven Backend
      run: mvn -B package --file tiendacomputoapi/pom.xml

    - name: Build, Push and Release a Docker container to Heroku Backend
      uses: gonuit/heroku-docker-deploy@v1.3.2 
      with:

          email: "italo_toribio@usmp.pe"

          heroku_api_key: "79e6ac2e-08e7-44ba-950e-029e604b71d7"
          
          heroku_app_name: "usmpcomputo-api"

          dockerfile_directory: ./tiendacomputoapi

          dockerfile_name: DockerFile

          docker_options: "--no-cache"

          process_type: web


  build_webapp:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven Frontend
      run: mvn -B package --file tiendacomputomvc/pom.xml

    - name: Build, Push and Release a Docker container to Heroku Frontend
      uses: gonuit/heroku-docker-deploy@v1.3.2 
      with:

          email: "italo_toribio@usmp.pe"

          heroku_api_key: "79e6ac2e-08e7-44ba-950e-029e604b71d7"
          
          heroku_app_name: "usmpcomputo-mvc"

          dockerfile_directory: ./tiendacomputomvc

          dockerfile_name: DockerFile

          docker_options: "--no-cache"

          process_type: web     
 